language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - sudo apt install -y libboost-dev
  - pip install -r requirements.txt codecov
# command to run tests
script:
  - py.test -n8 --cov=cigram
after_success:
  - codecov